### ISSUE TITLE
Output the C file to be checked by the model checker (transfer-function)

### ISSUE THREAD

**Issue by lucasccordeiro** [hussamaibrahim/dsverifier#19]
Output the C file to be checked by the model checker (transfer-function)

**Comment by lennonchaves** [comment]
There is a user request to include one DSVerifier (Digital-Systems Verifier) option to export the source code verified (i.e., without properties violation), in order to facilitate and to accelerate the development process.

This file should contain:

1) FXP Library with the basic operations.
2) The realization which was desired by User. 
3) Instructions about where the user could read the inputs and set the outputs.

This file must be supported by GCC compiler.
